import argparse
import json
import math
import random
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train a streaming-friendly LSTM activity classifier from pose keypoint "
            "sequences in JSON format (supports optional pseudo-labeling from unlabeled data)."
        )
    )
    parser.add_argument(
        "--data-json",
        type=str,
        default="datasets/pose_dummy_drilling_activity_v2.json",
        help="Path to dataset JSON generated by generate_drilling_pose_dummy_data.py",
    )
    parser.add_argument("--window-size", type=int, default=32)
    parser.add_argument("--stride", type=int, default=4)
    parser.add_argument("--min-kpt-conf", type=float, default=0.2)
    parser.add_argument("--val-ratio", type=float, default=0.2)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--hidden-size", type=int, default=128)
    parser.add_argument("--num-layers", type=int, default=2)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", type=str, default=None, help='e.g. "cpu", "cuda", "cuda:0"')
    parser.add_argument(
        "--exclude-labels",
        type=str,
        nargs="*",
        default=["unlabeled"],
        help="Labels to exclude from supervised training.",
    )
    parser.add_argument(
        "--label-scope",
        type=str,
        choices=["fine", "baseline"],
        default="fine",
        help=(
            "fine = keep detailed classes; "
            "baseline = map classes to {working, not_working, accident}."
        ),
    )
    parser.add_argument(
        "--use-unlabeled",
        action="store_true",
        help="Enable simple pseudo-label fine-tuning using unlabeled sessions.",
    )
    parser.add_argument(
        "--pseudo-threshold",
        type=float,
        default=0.94,
        help="Confidence threshold for selecting pseudo-labeled windows.",
    )
    parser.add_argument(
        "--pseudo-max-add",
        type=int,
        default=5000,
        help="Maximum pseudo-labeled windows to add.",
    )
    parser.add_argument(
        "--pseudo-epochs",
        type=int,
        default=5,
        help="Additional fine-tuning epochs on train+pseudo set.",
    )
    parser.add_argument(
        "--output-model",
        type=str,
        default="models/pose_activity_lstm.pt",
    )
    parser.add_argument(
        "--output-metadata",
        type=str,
        default="models/pose_activity_lstm_meta.json",
    )
    return parser.parse_args()


def _seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _to_float(v: Any, default: float = 0.0) -> float:
    try:
        if v is None or v == "":
            return default
        return float(v)
    except Exception:
        return default


def _to_int(v: Any, default: int = -1) -> int:
    try:
        if v is None or v == "":
            return default
        return int(float(v))
    except Exception:
        return default


def _choose_center(points_xy: np.ndarray, conf: np.ndarray, min_kpt_conf: float) -> np.ndarray:
    # COCO17 robust center: hips -> shoulders -> confidence centroid.
    idx_pairs = [(11, 12), (5, 6)]
    for a, b in idx_pairs:
        if a < len(points_xy) and b < len(points_xy):
            if conf[a] >= min_kpt_conf and conf[b] >= min_kpt_conf:
                return (points_xy[a] + points_xy[b]) / 2.0

    valid = conf >= min_kpt_conf
    if np.any(valid):
        return np.mean(points_xy[valid], axis=0)
    return np.mean(points_xy, axis=0)


def _choose_scale(points_xy: np.ndarray, conf: np.ndarray, bbox_h: float, min_kpt_conf: float) -> float:
    candidates: list[float] = []
    for a, b in [(5, 6), (11, 12), (5, 11), (6, 12)]:
        if a < len(points_xy) and b < len(points_xy):
            if conf[a] >= min_kpt_conf and conf[b] >= min_kpt_conf:
                d = float(np.linalg.norm(points_xy[a] - points_xy[b]))
                if d > 1e-6:
                    candidates.append(d)
    if bbox_h > 1e-6:
        candidates.append(float(bbox_h))
    if not candidates:
        return 1.0
    return max(float(np.median(candidates)), 1e-3)


def normalize_frame(keypoints_xyc: np.ndarray, bbox_h: float, min_kpt_conf: float) -> np.ndarray:
    points_xy = keypoints_xyc[:, :2].copy()
    conf = keypoints_xyc[:, 2].copy()
    points_xy = np.nan_to_num(points_xy, nan=0.0, posinf=0.0, neginf=0.0)
    conf = np.nan_to_num(conf, nan=0.0, posinf=0.0, neginf=0.0)

    center = _choose_center(points_xy, conf, min_kpt_conf=min_kpt_conf)
    scale = _choose_scale(points_xy, conf, bbox_h=bbox_h, min_kpt_conf=min_kpt_conf)
    norm_xy = (points_xy - center) / scale
    return np.concatenate([norm_xy, conf[:, None]], axis=1).astype(np.float32)


def load_rows_from_json(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    samples = payload.get("samples", [])
    if not isinstance(samples, list) or not samples:
        raise ValueError(f"No usable 'samples' found in {path}")

    rows: list[dict[str, Any]] = []
    for s in samples:
        kpts = s.get("keypoints", [])
        if not isinstance(kpts, list) or not kpts:
            continue

        k_max = max(_to_int(k.get("kpt_index"), i) for i, k in enumerate(kpts)) + 1
        arr = np.zeros((k_max, 3), dtype=np.float32)
        arr[:, 0] = np.nan
        arr[:, 1] = np.nan

        for i, kp in enumerate(kpts):
            k_idx = _to_int(kp.get("kpt_index"), i)
            if 0 <= k_idx < k_max:
                arr[k_idx, 0] = _to_float(kp.get("x"), default=np.nan)
                arr[k_idx, 1] = _to_float(kp.get("y"), default=np.nan)
                arr[k_idx, 2] = _to_float(kp.get("conf"), default=0.0)

        bbox = s.get("bbox", {})
        rows.append(
            {
                "session_name": str(s.get("session_name", "unknown_session")),
                "frame_index": _to_int(s.get("frame_index"), default=0),
                "activity_label": str(s.get("activity_label", "unknown")),
                "person_id": _to_int(s.get("person_id"), default=-1),
                "bbox_h": _to_float(bbox.get("h"), default=1.0),
                "keypoints_xyc": arr,
            }
        )
    return rows


def map_to_baseline(label: str) -> str:
    l = label.strip().lower()
    if l in {"manual_working", "drilling_operation", "pipe_handling"}:
        return "working"
    if l in {"falling", "lying"}:
        return "accident"
    if l in {"standing", "walking", "sitting", "crouching", "bending"}:
        return "not_working"
    return l


def build_windows(
    rows: list[dict[str, Any]],
    window_size: int,
    stride: int,
    min_kpt_conf: float,
    exclude_labels: set[str],
    label_scope: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    grouped: dict[tuple[str, int, str], list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        grouped[(r["session_name"], r["person_id"], r["activity_label"])].append(r)

    x_sup: list[np.ndarray] = []
    y_sup: list[str] = []
    g_sup: list[str] = []
    x_unsup: list[np.ndarray] = []

    for (session_name, _pid, label), seq in grouped.items():
        mapped_label = map_to_baseline(label) if label_scope == "baseline" else label
        seq = sorted(seq, key=lambda z: z["frame_index"])
        if len(seq) < window_size:
            continue

        norm = [
            normalize_frame(
                keypoints_xyc=s["keypoints_xyc"],
                bbox_h=s["bbox_h"],
                min_kpt_conf=min_kpt_conf,
            )
            for s in seq
        ]
        arr = np.stack(norm, axis=0)  # [T, K, 3]

        for start in range(0, len(arr) - window_size + 1, stride):
            w = arr[start : start + window_size]
            if label in exclude_labels:
                x_unsup.append(w)
            else:
                x_sup.append(w)
                y_sup.append(mapped_label)
                g_sup.append(session_name)

    if x_sup:
        x_sup_arr = np.stack(x_sup, axis=0).astype(np.float32)
        y_sup_arr = np.asarray(y_sup)
        g_sup_arr = np.asarray(g_sup)
    else:
        x_sup_arr = np.empty((0, window_size, 0, 3), dtype=np.float32)
        y_sup_arr = np.empty((0,), dtype="<U1")
        g_sup_arr = np.empty((0,), dtype="<U1")

    if x_unsup:
        x_unsup_arr = np.stack(x_unsup, axis=0).astype(np.float32)
    else:
        x_unsup_arr = np.empty((0, window_size, 0, 3), dtype=np.float32)

    return x_sup_arr, y_sup_arr, g_sup_arr, x_unsup_arr


def group_split(
    groups: np.ndarray,
    val_ratio: float,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    uniq = sorted(set(groups.tolist()))
    if len(uniq) < 2:
        idx = np.arange(len(groups))
        return idx, np.empty((0,), dtype=np.int64)

    rng = random.Random(seed)
    rng.shuffle(uniq)
    n_val = max(1, int(math.ceil(len(uniq) * val_ratio)))
    val_groups = set(uniq[:n_val])

    train_idx = np.asarray([i for i, g in enumerate(groups) if g not in val_groups], dtype=np.int64)
    val_idx = np.asarray([i for i, g in enumerate(groups) if g in val_groups], dtype=np.int64)
    return train_idx, val_idx


class SequenceDataset(Dataset):
    def __init__(self, x: np.ndarray, y: np.ndarray):
        self.x = x
        self.y = y

    def __len__(self) -> int:
        return int(len(self.x))

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        x_t = torch.tensor(self.x[idx].tolist(), dtype=torch.float32)
        y_t = torch.tensor(int(self.y[idx]), dtype=torch.long)
        return x_t, y_t


class LSTMActivityClassifier(nn.Module):
    def __init__(
        self,
        kpt_count: int,
        hidden_size: int,
        num_layers: int,
        dropout: float,
        num_classes: int,
    ):
        super().__init__()
        input_size = kpt_count * 3
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.LayerNorm(hidden_size),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [B, T, K, 3]
        b, t, k, c = x.shape
        z = x.reshape(b, t, k * c)
        out, _ = self.lstm(z)
        last = out[:, -1, :]
        logits = self.head(last)
        return logits


def evaluate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
) -> tuple[float, float]:
    model.eval()
    total_loss = 0.0
    total = 0
    correct = 0
    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)
            y = y.to(device)
            logits = model(x)
            loss = criterion(logits, y)

            total_loss += float(loss.item()) * y.size(0)
            preds = torch.argmax(logits, dim=1)
            correct += int((preds == y).sum().item())
            total += int(y.size(0))

    if total == 0:
        return 0.0, 0.0
    return total_loss / total, correct / total


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> tuple[float, float]:
    model.train()
    total_loss = 0.0
    total = 0
    correct = 0
    for x, y in loader:
        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad(set_to_none=True)
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)
        optimizer.step()

        total_loss += float(loss.item()) * y.size(0)
        preds = torch.argmax(logits, dim=1)
        correct += int((preds == y).sum().item())
        total += int(y.size(0))

    return (total_loss / total, correct / total) if total > 0 else (0.0, 0.0)


def select_pseudo_labels(
    model: nn.Module,
    x_unlabeled: np.ndarray,
    batch_size: int,
    threshold: float,
    max_add: int,
    device: torch.device,
) -> tuple[np.ndarray, np.ndarray]:
    if len(x_unlabeled) == 0:
        return np.empty((0,), dtype=np.int64), np.empty((0,), dtype=np.int64)

    model.eval()
    sel_idx: list[int] = []
    sel_y: list[int] = []
    with torch.no_grad():
        for start in range(0, len(x_unlabeled), batch_size):
            end = min(len(x_unlabeled), start + batch_size)
            x = torch.tensor(
                x_unlabeled[start:end].tolist(),
                dtype=torch.float32,
                device=device,
            )
            probs = torch.softmax(model(x), dim=1)
            conf, pred = torch.max(probs, dim=1)
            keep = conf >= threshold
            keep_np = keep.cpu().tolist()
            pred_np = pred.cpu().tolist()
            for i, k in enumerate(keep_np):
                if k:
                    sel_idx.append(start + i)
                    sel_y.append(int(pred_np[i]))
                    if len(sel_idx) >= max_add:
                        return np.asarray(sel_idx, dtype=np.int64), np.asarray(sel_y, dtype=np.int64)

    return np.asarray(sel_idx, dtype=np.int64), np.asarray(sel_y, dtype=np.int64)


def main() -> None:
    args = parse_args()
    _seed_everything(args.seed)

    device = (
        torch.device(args.device)
        if args.device
        else torch.device("cuda" if torch.cuda.is_available() else "cpu")
    )

    rows = load_rows_from_json(Path(args.data_json))
    x_sup, y_sup_str, groups, x_unsup = build_windows(
        rows=rows,
        window_size=args.window_size,
        stride=args.stride,
        min_kpt_conf=args.min_kpt_conf,
        exclude_labels=set(args.exclude_labels),
        label_scope=args.label_scope,
    )

    if len(x_sup) == 0:
        raise RuntimeError(
            "No supervised windows found. Check labels and window size. "
            f"exclude_labels={args.exclude_labels}, window_size={args.window_size}"
        )

    labels = sorted(set(y_sup_str.tolist()))
    if len(labels) < 2:
        raise RuntimeError(f"Need at least 2 classes, got {labels}")
    label_to_idx = {name: i for i, name in enumerate(labels)}
    idx_to_label = {i: name for name, i in label_to_idx.items()}
    y_sup = np.asarray([label_to_idx[s] for s in y_sup_str], dtype=np.int64)

    train_idx, val_idx = group_split(groups=groups, val_ratio=args.val_ratio, seed=args.seed)
    if len(train_idx) == 0 or len(val_idx) == 0:
        raise RuntimeError(
            "Train/val split failed. Try collecting more sessions or lowering val_ratio."
        )

    x_train, y_train = x_sup[train_idx], y_sup[train_idx]
    x_val, y_val = x_sup[val_idx], y_sup[val_idx]

    class_counts = Counter(y_train.tolist())
    weights = np.ones((len(labels),), dtype=np.float32)
    for c_idx in range(len(labels)):
        weights[c_idx] = 1.0 / max(class_counts.get(c_idx, 1), 1)
    weights = weights / np.mean(weights)
    class_weights = torch.tensor(weights, dtype=torch.float32, device=device)

    train_loader = DataLoader(
        SequenceDataset(x_train, y_train),
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=False,
    )
    val_loader = DataLoader(
        SequenceDataset(x_val, y_val),
        batch_size=args.batch_size,
        shuffle=False,
        drop_last=False,
    )

    kpt_count = int(x_sup.shape[2])
    model = LSTMActivityClassifier(
        kpt_count=kpt_count,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
        num_classes=len(labels),
    ).to(device)

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(args.epochs, 1), eta_min=args.lr * 0.1
    )

    best_val_acc = -1.0
    best_state = None
    no_improve = 0
    patience = 8

    print(f"Device: {device}")
    print(f"Supervised windows: {len(x_sup)} | Unlabeled windows: {len(x_unsup)}")
    print(f"Train windows: {len(x_train)} | Val windows: {len(x_val)}")
    print(f"Classes: {labels}")

    for epoch in range(1, args.epochs + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        va_loss, va_acc = evaluate(model, val_loader, criterion, device)
        scheduler.step()

        print(
            f"Epoch {epoch:03d}/{args.epochs} "
            f"| train loss {tr_loss:.4f} acc {tr_acc:.4f} "
            f"| val loss {va_loss:.4f} acc {va_acc:.4f}"
        )

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= patience:
                print(f"Early stop at epoch {epoch} (patience={patience})")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    pseudo_added = 0
    if args.use_unlabeled and len(x_unsup) > 0:
        sel_idx, sel_y = select_pseudo_labels(
            model=model,
            x_unlabeled=x_unsup,
            batch_size=args.batch_size,
            threshold=args.pseudo_threshold,
            max_add=args.pseudo_max_add,
            device=device,
        )
        pseudo_added = int(len(sel_idx))
        print(
            f"Pseudo-label selection: threshold={args.pseudo_threshold}, "
            f"selected={pseudo_added}/{len(x_unsup)}"
        )

        if pseudo_added > 0 and args.pseudo_epochs > 0:
            x_aug = np.concatenate([x_train, x_unsup[sel_idx]], axis=0)
            y_aug = np.concatenate([y_train, sel_y], axis=0)

            aug_loader = DataLoader(
                SequenceDataset(x_aug, y_aug),
                batch_size=args.batch_size,
                shuffle=True,
                drop_last=False,
            )

            ft_optimizer = torch.optim.AdamW(
                model.parameters(),
                lr=args.lr * 0.5,
                weight_decay=args.weight_decay,
            )

            for pe in range(1, args.pseudo_epochs + 1):
                tr_loss, tr_acc = train_one_epoch(
                    model, aug_loader, criterion, ft_optimizer, device
                )
                va_loss, va_acc = evaluate(model, val_loader, criterion, device)
                print(
                    f"Pseudo Epoch {pe:02d}/{args.pseudo_epochs} "
                    f"| train loss {tr_loss:.4f} acc {tr_acc:.4f} "
                    f"| val loss {va_loss:.4f} acc {va_acc:.4f}"
                )

    out_model = Path(args.output_model)
    out_meta = Path(args.output_metadata)
    out_model.parent.mkdir(parents=True, exist_ok=True)
    out_meta.parent.mkdir(parents=True, exist_ok=True)

    ckpt = {
        "model_state_dict": model.state_dict(),
        "label_to_idx": label_to_idx,
        "idx_to_label": idx_to_label,
        "config": {
            "window_size": args.window_size,
            "min_kpt_conf": args.min_kpt_conf,
            "kpt_count": kpt_count,
            "hidden_size": args.hidden_size,
            "num_layers": args.num_layers,
            "dropout": args.dropout,
        },
    }
    torch.save(ckpt, out_model)

    metrics = {
        "data_json": args.data_json,
        "label_scope": args.label_scope,
        "window_size": args.window_size,
        "stride": args.stride,
        "min_kpt_conf": args.min_kpt_conf,
        "labels": labels,
        "device": str(device),
        "supervised_windows": int(len(x_sup)),
        "unlabeled_windows": int(len(x_unsup)),
        "train_windows": int(len(x_train)),
        "val_windows": int(len(x_val)),
        "best_val_acc": float(best_val_acc),
        "pseudo_enabled": bool(args.use_unlabeled),
        "pseudo_added": int(pseudo_added),
        "output_model": str(out_model),
    }
    with out_meta.open("w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    print(f"Saved model: {out_model}")
    print(f"Saved metadata: {out_meta}")


if __name__ == "__main__":
    main()
